report :
	xelatex ./doc/report.tex
	rm report.aux
	rm report.log

slide :
	xelatex ./doc/slide.tex
	rm slide.log
	rm slide.out
	rm slide.snm
	rm slide.aux
	rm slide.nav
	rm slide.toc

clear :
	rm report.pdf
	rm slide.pdf
